### ISSUE TITLE
操作协调 & 类型错误

### ISSUE THREAD

**Issue by chttiu** [shiux-lab/Enneagram#4]
1. 其实我感觉这样不太协调，我觉得一开始就不要显示题了，给个开始按钮，点了之后就弹窗让用户登录

2. EnneagramChart  处有 @ts-ignore  `const labels = [...tm('enneagram.labels')] `， 你能怎么让他类型正确吗，我搞不定

**Comment by shiux-lab** [comment]
tm 本来就没法类型正确

**Comment by chttiu** [comment]
> tm 本来就没法类型正确

不可以讲脏话🙅
